mysql: &mysql
  adapter: mysql2
  encoding: utf8
  host: localhost
  reconnect: true
  pool: 5
  username: ""
  password: ""

development:
  <<: *mysql
  database: <application>_development

test:
  <<: *mysql
  database: <application>_test

production:
  <<: *mysql
  database: <application>_production
