require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Bundler/OrderedGems:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*.rb'

Rails/WhereExists:
  Enabled: false
  
Rails/BulkChangeTable:
  Enabled: false  

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/NonNilCheck:
  IncludeSemanticChanges: true

Style/HashEachMethods:
  Enabled: true

Style/HashSyntax:
  Enabled: true
  EnforcedShorthandSyntax: either

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/environments/**/*.rb'
    - 'config/routes.rb'
    - 'db/**/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Rails/NotNullColumn:
  Exclude:
    - 'db/migrate/*'

Rails/I18nLocaleAssignment:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc
  
Metrics/ClassLength:
  CountAsOne:
    - array
    - hash
    - heredoc
  Exclude:
    - 'db/**/*'

Naming/InclusiveLanguage:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/system/**/*'
    - 'spec/views/**/*'

RSpec/DescribedClass:
  SkipBlocks: true

RSpec/ExampleLength:
  Exclude:
    - 'spec/system/**/*'
    - 'spec/requests/**/*'
    - 'spec/views/**/*'

RSpec/InstanceVariable:
  Exclude:
    - 'spec/views/**/*'

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Enabled: false
  
RSpec/NoExpectationExample:  
  Enabled: false

RSpec/SortMetadata:
  Enabled: false
  
RSpec/AnyInstance:
  Enabled: false
  
RSpec/VerifiedDoubles:
  Enabled: false  

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'script/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
