Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Exclude:
  - 'bin/setup'
  - 'bin/update'

Style/NonNilCheck:
  IncludeSemanticChanges: true

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*.rb'

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'script/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
