Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/NonNilCheck:
  IncludeSemanticChanges: true

Naming/PredicateName:
  Exclude:
    - 'app/serializers/**/*'

Metrics/BlockLength:
  Exclude:
  - config/initializers/simple_form_bootstrap.rb
  - 'Rakefile'
  - '**/*.rake'
  - 'spec/**/*.rb'

Naming/FileName:
  Exclude:
  - 'Gemfile'

Style/FrozenStringLiteralComment:
  Enabled: false
  
Style/FormatStringToken:
  Enabled: false  

Rails/LexicallyScopedActionFilter:
  Enabled: false  

AllCops:
  TargetRailsVersion: 5.1
  TargetRubyVersion: 2.4
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'script/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'config/unicorn.rb'
    - 'db/**/*'
    - 'vendor/bundle/**/*'
    - 'node_modules/**/*'
