inherit_gem:
  renuocop: config/base.yml

# most likely you would like to copy and adjust the `AllCops` part (e.g. to exclude vendor-files)
# AllCops:
#   NewCops: enable
#   Exclude:
#     - 'vendor/**/*'
#     ... and add all the exclusions from the `config/base.yml`

