require:
  - rubocop-performance
  - rubocop-rspec

Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
  - 'bin/setup'
  - 'bin/update'

Style/NonNilCheck:
  IncludeSemanticChanges: true

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*.rb'
  - 'config/environments/**/*.rb'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/system/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/system/**/*'
    - 'spec/requests/**/*'

RSpec/NestedGroups:
  Max: 5

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'script/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
